name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  # lint:
  #   runs-on: ubuntu-latest
  #   needs: setup-and-test
    
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
        
  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.9

  #     - name: Install flake8
  #       run: |
  #         pip install flake8

  #     - name: Run Linting
  #       run: |
  #         flake8 src/ tests/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: lint

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Deploy to Production (Dummy Step)
  #       run: echo "Deploying to production"